### ISSUE TITLE
jamovi 1.2.0.0

### ISSUE THREAD

**Issue by cwendorf** [rcalinjageman/esci#1]
esci.jmo is no longer compatible with the newest version of jamovi (1.2.0.0).: (

**Comment by rcalinjageman** [comment]
Apparently there have been some changes with 1.2.0.0.  I now have esci compiling--you'll find a new .jmo file that seems to be working with 1.2.0.0:    	esci_0.0.0-win64-R3.6.1.jmo

From the file name it looks like this updated .jmo may only work on Windows?  Not sure because I don't have another OS at hand to test.  But at least for Windows downloading this will work.  

Direct link to updated module for 1.2.0.0:  https://tinyurl.com/esci-updated 
This link will continue to point to module for older versions: https://tinyurl.com/esci-old
