### ISSUE TITLE
UseMethod fails for estimateMeanDifference()

### ISSUE THREAD

**Issue by LukasWallrich** [rcalinjageman/esci#4]
I am just following your SIPS session, but the code does not run in my R. From 
`  estimate <- estimateMeanDifference(cdata, sex, d_art)
`
I get 
```
Error in UseMethod("estimateMeanDifference") : 
  no applicable method for 'estimateMeanDifference' applied to an object of class "data.frame"
```

Using esci:::estimateMeanDifference.default() works. I am using R 4.0.1.

Thanks for this wonderful work!

**Comment by rcalinjageman** [comment]
Sorry for a 3 year delay in responding!  
 I've now completely rewritten esci.  The R package is here on github; the jamovi module is available in the jamovi module library (esci 1.01; you need at least jamovi 2.4 to install it). In the updated version, the relevant function is estimate_mdiff_two, and the order of inputs is now updated so that the command would become estimate_mdiff_two(cdata, d_art, sex)  If still interested, let me know what you think!
